import type {SocialRepository} from './SocialRepository';import type {FriendshipState,LeaderboardEntry,Page,PlayerRankSnapshot,PublicPlayerProfile,RankingCategory,RankingPeriod,RankingScope,SocialActivityEvent} from './types';import {rankPlayers} from './ranking';import {sanitizeActivityForPublic} from './activity';
export class InMemorySocialRepository implements SocialRepository{private profiles=new Map<string,PublicPlayerProfile>();private following=new Set<string>();private blocked=new Set<string>();private friends=new Map<string,FriendshipState>();private events:SocialActivityEvent[]=[];constructor(seed:PublicPlayerProfile[]=[]){for(const p of seed)this.profiles.set(p.playerId,p);}
async getPublicProfile(id:string){return this.blocked.has(id)?null:this.profiles.get(id)??null;}async searchPlayers(q:string,cursor?:string):Promise<Page<PublicPlayerProfile>>{const x=q.trim().toLowerCase();return page([...this.profiles.values()].filter(p=>!this.blocked.has(p.playerId)&&p.visibility==='PUBLIC'&&(p.displayName.toLowerCase().includes(x)||p.playerId.toLowerCase().includes(x))),cursor);}
async follow(id:string){this.assertTarget(id);this.following.add(id);}async unfollow(id:string){this.following.delete(id);}async block(id:string){this.following.delete(id);this.friends.set(id,'BLOCKED');this.blocked.add(id);}async unblock(id:string){this.blocked.delete(id);if(this.friends.get(id)==='BLOCKED')this.friends.set(id,'NONE');}
async getCounts(){return{followers:0,following:this.following.size,friends:[...this.friends.values()].filter(x=>x==='FRIENDS').length};}async getFriendship(id:string){return this.friends.get(id)??'NONE';}async sendFriendRequest(id:string){this.assertTarget(id);const s=await this.getFriendship(id);if(s==='NONE')this.friends.set(id,'REQUEST_SENT');}async acceptFriendRequest(id:string){if(await this.getFriendship(id)!=='REQUEST_RECEIVED')throw new Error('NO_REQUEST');this.friends.set(id,'FRIENDS');}async removeFriend(id:string){if(await this.getFriendship(id)==='FRIENDS')this.friends.set(id,'NONE');}
async getLeaderboard(_s:RankingScope,c:RankingCategory,_p:RankingPeriod,cursor?:string):Promise<Page<LeaderboardEntry>>{return page(rankPlayers([...this.profiles.values()].filter(p=>p.visibility==='PUBLIC'&&!this.blocked.has(p.playerId)).map(player=>({player,verification:'UNVERIFIED'})),c),cursor);}
async getPlayerRank(id:string,c:RankingCategory,p:RankingPeriod):Promise<PlayerRankSnapshot>{const all=(await this.getLeaderboard('GLOBAL',c,p)).items,pos=all.find(x=>x.player.playerId===id)?.position??null;return{global:pos,country:null,city:null,friends:null,category:c,period:p,generatedAt:new Date().toISOString()};}
async getActivityFeed(cursor?:string){return page(this.events.filter(e=>e.visibility==='PUBLIC').map(sanitizeActivityForPublic),cursor);}addActivity(e:SocialActivityEvent){this.events.unshift(e);}private assertTarget(id:string){if(this.blocked.has(id))throw new Error('BLOCKED');if(!this.profiles.has(id))throw new Error('NOT_FOUND');}}
function page<T>(all:T[],cursor?:string,size=25):Page<T>{const start=Math.max(0,Number(cursor)||0),items=all.slice(start,start+size),next=start+items.length<all.length?String(start+items.length):null;return{items,nextCursor:next};}
