export const PRESENTATION_SOCIAL_VERSION='1.0.0';
export const PRESENTATION_SOCIAL_CAPABILITIES=['CANONICAL_EVENTS','SHARE_PRIVACY','LEADERBOARD','GUILDS','RAIDS','WORLD_SIGNALS'] as const;
export function presentationSocialBuild(){return {version:PRESENTATION_SOCIAL_VERSION,capabilities:[...PRESENTATION_SOCIAL_CAPABILITIES]};}
