import type { RunnableQuest } from './types';

export const FIELD_TEST_QUESTS: readonly RunnableQuest[] = [
  {
    id: 'field_test_walk_500m',
    title: 'FIELD TEST: WALK 500M',
    description: 'Walk 500 meters outdoors. SYSTEM tracks GPS distance. Keep the app open and screen on.',
    category: 'DAILY',
    difficulty: 'EASY',
    order: 100,
    primarySkill: 'VIT',
    secondarySkills: [],
    verification: {
      type: 'GPS_DISTANCE',
      minimumDistanceMeters: 500,
      verificationScoreRequired: 70,
    },
    activityType: 'WALK',
    verificationStrength: 'STANDARD',
    rewards: { realXp: 50, skillXp: { VIT: 30 }, gameEnergy: 5 },
    progress: 0,
    progressTarget: 500,
    createdAt: new Date().toISOString(),
    arc: 'FIELD_TEST',
    chapter: 99,
    hidden: true,
  },
  {
    id: 'field_test_walk_1km',
    title: 'FIELD TEST: WALK 1KM',
    description: 'Walk 1 kilometer outdoors. SYSTEM tracks GPS distance. Keep the app open and screen on.',
    category: 'DAILY',
    difficulty: 'NORMAL',
    order: 101,
    primarySkill: 'VIT',
    secondarySkills: ['WIL'],
    verification: {
      type: 'GPS_DISTANCE',
      minimumDistanceMeters: 1000,
      verificationScoreRequired: 70,
    },
    activityType: 'WALK',
    verificationStrength: 'STANDARD',
    rewards: { realXp: 100, skillXp: { VIT: 50, WIL: 30 }, gameEnergy: 10 },
    progress: 0,
    progressTarget: 1000,
    createdAt: new Date().toISOString(),
    arc: 'FIELD_TEST',
    chapter: 99,
    hidden: true,
  },
  {
    id: 'field_test_timer_10min',
    title: 'FIELD TEST: MOVE 10 MIN',
    description: 'Stay active for 10 minutes. Timer confirms time in SYSTEM, not quality of work.',
    category: 'DAILY',
    difficulty: 'EASY',
    order: 102,
    primarySkill: 'WIL',
    secondarySkills: [],
    verification: {
      type: 'TIMER',
      minimumDurationSeconds: 600,
      verificationScoreRequired: 100,
    },
    activityType: undefined,
    verificationStrength: 'STANDARD',
    rewards: { realXp: 60, skillXp: { WIL: 40 }, gameEnergy: 5 },
    progress: 0,
    progressTarget: 600,
    createdAt: new Date().toISOString(),
    arc: 'FIELD_TEST',
    chapter: 99,
    hidden: true,
  },
  {
    id: 'field_test_multi_500m_5min',
    title: 'FIELD TEST: 500M + 5 MIN',
    description: 'Walk 500 meters AND stay active for 5 minutes. Both conditions required.',
    category: 'DAILY',
    difficulty: 'NORMAL',
    order: 103,
    primarySkill: 'VIT',
    secondarySkills: ['WIL'],
    verification: {
      type: 'MULTI',
      minimumDistanceMeters: 500,
      minimumDurationSeconds: 300,
      verificationScoreRequired: 70,
    },
    activityType: 'WALK',
    verificationStrength: 'STANDARD',
    rewards: { realXp: 120, skillXp: { VIT: 50, WIL: 50 }, gameEnergy: 15 },
    progress: 0,
    progressTarget: 500,
    createdAt: new Date().toISOString(),
    arc: 'FIELD_TEST',
    chapter: 99,
    hidden: true,
  },
];

export const FIELD_TEST_QUEST_IDS = FIELD_TEST_QUESTS.map(q => q.id);

export function isFieldTestQuest(questId: string): boolean {
  return FIELD_TEST_QUEST_IDS.includes(questId);
}