import {getValidSession} from './auth';import {cloudRequest} from './http';import type {FriendshipState,SocialActivityEvent,SocialCounts} from '../social';
async function session(){const s=await getValidSession();if(!s)throw new Error('Najpierw zaloguj SYSTEM CLOUD.');return s;}
export async function blockSocialPlayer(id:string){const s=await session();await cloudRequest('/rest/v1/rpc/block_social_player',{method:'POST',body:JSON.stringify({p_target:id})},s.accessToken);}
export async function unblockSocialPlayer(id:string){const s=await session();await cloudRequest('/rest/v1/social_blocks?blocker_id=eq.'+encodeURIComponent(s.user.id)+'&blocked_id=eq.'+encodeURIComponent(id),{method:'DELETE'},s.accessToken);}
export async function sendCloudFriendRequest(id:string){const s=await session();if(id===s.user.id)throw new Error('SELF_FRIEND');await cloudRequest('/rest/v1/rpc/send_friend_request',{method:'POST',body:JSON.stringify({p_target:id})},s.accessToken);}
export async function respondCloudFriendRequest(senderId:string,accept:boolean){const s=await session();await cloudRequest('/rest/v1/rpc/respond_friend_request',{method:'POST',body:JSON.stringify({p_sender:senderId,p_accept:accept})},s.accessToken);}
export async function getCloudFriendship(id:string):Promise<FriendshipState>{const s=await session();const rows=await cloudRequest<{sender_id:string;receiver_id:string;status:string}[]>('/rest/v1/friend_requests?or=(and(sender_id.eq.'+s.user.id+',receiver_id.eq.'+id+'),and(sender_id.eq.'+id+',receiver_id.eq.'+s.user.id+'))&select=sender_id,receiver_id,status&limit=1',{method:'GET'},s.accessToken);const r=rows[0];if(!r)return'NONE';if(r.status==='accepted')return'FRIENDS';return r.sender_id===s.user.id?'REQUEST_SENT':'REQUEST_RECEIVED';}
export async function publishVerifiedQuestActivity(eventKey:string){const s=await session();const key=eventKey.trim();if(!/^verified:[A-Za-z0-9._:-]{1,180}$/.test(key))throw new Error('Nieprawidłowy klucz zweryfikowanego zdarzenia.');await cloudRequest('/rest/v1/rpc/publish_verified_social_activity',{method:'POST',body:JSON.stringify({p_event_key:key})},s.accessToken);}
export async function publishSocialActivity(event:Omit<SocialActivityEvent,'id'|'playerId'>){const key=event.metadata?.eventKey;if(event.type!=='QUEST_COMPLETED'||typeof key!=='string')throw new Error('Activity Feed przyjmuje tylko zdarzenia potwierdzone przez SYSTEM CLOUD.');await publishVerifiedQuestActivity(key);}
export async function getCloudSocialCounts():Promise<SocialCounts>{const s=await session();const [a,b,c]=await Promise.all([cloudRequest<{count:number|string}[]>('/rest/v1/rpc/social_followers_count',{method:'POST',body:'{}'},s.accessToken).catch(()=>[{count:0}]),cloudRequest<{count:number|string}[]>('/rest/v1/rpc/social_following_count',{method:'POST',body:'{}'},s.accessToken).catch(()=>[{count:0}]),cloudRequest<{count:number|string}[]>('/rest/v1/rpc/social_friends_count',{method:'POST',body:'{}'},s.accessToken).catch(()=>[{count:0}])]);return{followers:Number(a[0]?.count??0)||0,following:Number(b[0]?.count??0)||0,friends:Number(c[0]?.count??0)||0};}
export type CloudFriendRow={user_id:string;handle:string|null;public_name:string|null;real_level:number;rank:string;status:'REQUEST_SENT'|'REQUEST_RECEIVED'|'FRIENDS'};
export async function getCloudFriendNetwork():Promise<CloudFriendRow[]>{const s=await session();return cloudRequest<CloudFriendRow[]>('/rest/v1/rpc/get_friend_network',{method:'POST',body:'{}'},s.accessToken);}
export async function removeCloudFriend(id:string){const s=await session();await cloudRequest('/rest/v1/rpc/remove_friend',{method:'POST',body:JSON.stringify({p_target:id})},s.accessToken);}
