-- SYSTEM SOCIAL CORE 1.0 expansion. Additive; existing online03 contracts remain valid.
create table if not exists public.social_blocks(blocker_id uuid not null references auth.users(id) on delete cascade,blocked_id uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),primary key(blocker_id,blocked_id),constraint social_blocks_no_self check(blocker_id<>blocked_id));
create table if not exists public.friend_requests(sender_id uuid not null references auth.users(id) on delete cascade,receiver_id uuid not null references auth.users(id) on delete cascade,status text not null default 'pending' check(status in('pending','accepted','rejected','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(sender_id,receiver_id),constraint friend_requests_no_self check(sender_id<>receiver_id));
create table if not exists public.social_activity(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,event_type text not null,visibility text not null default 'public' check(visibility in('public','friends','private')),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists social_activity_user_created_idx on public.social_activity(user_id,created_at desc);
alter table public.social_blocks enable row level security;alter table public.friend_requests enable row level security;alter table public.social_activity enable row level security;
revoke all on public.social_blocks,public.friend_requests,public.social_activity from anon,authenticated;grant select,insert,delete on public.social_blocks to authenticated;grant select,insert,update,delete on public.friend_requests to authenticated;grant select,insert on public.social_activity to authenticated;
create policy social_blocks_related on public.social_blocks for select to authenticated using(blocker_id=(select auth.uid()) or blocked_id=(select auth.uid()));
create policy social_blocks_own_insert on public.social_blocks for insert to authenticated with check(blocker_id=(select auth.uid()));
create policy social_blocks_own_delete on public.social_blocks for delete to authenticated using(blocker_id=(select auth.uid()));
create policy friend_requests_related on public.friend_requests for select to authenticated using(sender_id=(select auth.uid()) or receiver_id=(select auth.uid()));
create policy friend_requests_sender_insert on public.friend_requests for insert to authenticated with check(sender_id=(select auth.uid()) and not exists(select 1 from public.social_blocks b where (b.blocker_id=sender_id and b.blocked_id=receiver_id) or (b.blocker_id=receiver_id and b.blocked_id=sender_id)));
create policy friend_requests_related_update on public.friend_requests for update to authenticated using(sender_id=(select auth.uid()) or receiver_id=(select auth.uid())) with check(sender_id=(select auth.uid()) or receiver_id=(select auth.uid()));
create policy social_activity_visible on public.social_activity for select to authenticated using(user_id=(select auth.uid()) or visibility='public');
create policy social_activity_own_insert on public.social_activity for insert to authenticated with check(user_id=(select auth.uid()));
create or replace function public.block_social_player(p_target uuid) returns void language plpgsql security invoker set search_path='' as $$ begin if p_target=(select auth.uid()) then raise exception 'SELF_BLOCK'; end if; insert into public.social_blocks(blocker_id,blocked_id) values((select auth.uid()),p_target) on conflict do nothing; delete from public.follows where (follower_id=(select auth.uid()) and followed_id=p_target) or (follower_id=p_target and followed_id=(select auth.uid())); delete from public.friend_requests where (sender_id=(select auth.uid()) and receiver_id=p_target) or (sender_id=p_target and receiver_id=(select auth.uid())); end; $$;
revoke all on function public.block_social_player(uuid) from public,anon;grant execute on function public.block_social_player(uuid) to authenticated;
