import type {MoveQuest} from './types';
const ALL=['AGE_6_8','AGE_9_12','AGE_13_17','ADULT'] as const;
export const MOVE_QUESTS:MoveQuest[]=[
{id:'move_walk_10',title:'SCOUT WALK',description:'10 minut energicznego spaceru.',kind:'WALK',minutes:10,skills:['ENDURANCE'],verification:'GPS_DISTANCE',difficulty:'EASY',ageModes:[...ALL],outdoor:true,familyEligible:true},
{id:'move_run_10',title:'RUN SIGNAL',description:'10 minut spokojnego biegu lub marszobiegu.',kind:'RUN',minutes:10,skills:['SPEED','ENDURANCE'],verification:'GPS_DISTANCE',difficulty:'NORMAL',ageModes:['AGE_9_12','AGE_13_17','ADULT'],outdoor:true,familyEligible:true},
{id:'move_jump_5',title:'JUMP ANOMALY',description:'Krótka seria bezpiecznych skoków z przerwami.',kind:'JUMP',minutes:5,skills:['JUMP','COORDINATION'],verification:'TIMER',difficulty:'EASY',ageModes:['AGE_6_8','AGE_9_12','AGE_13_17'],outdoor:false,familyEligible:true},
{id:'move_balance_5',title:'BALANCE CORE',description:'Proste zadania równoważne i przejścia po wyznaczonej linii.',kind:'BALANCE',minutes:5,skills:['BALANCE','COORDINATION'],verification:'TIMER',difficulty:'EASY',ageModes:['AGE_6_8','AGE_9_12','AGE_13_17'],outdoor:false,familyEligible:true},
{id:'move_ball_10',title:'BALL CONTROL',description:'Rzuty i łapanie piłki w bezpiecznej przestrzeni.',kind:'BALL',minutes:10,skills:['THROW','CATCH','COORDINATION'],verification:'PARENT_APPROVAL',difficulty:'EASY',ageModes:['AGE_6_8','AGE_9_12'],outdoor:false,familyEligible:true},
{id:'move_bike_20',title:'BIKE PATROL',description:'20 minut spokojnej jazdy rowerem w bezpiecznym miejscu.',kind:'BIKE',minutes:20,skills:['ENDURANCE','COORDINATION'],verification:'GPS_DISTANCE',difficulty:'NORMAL',ageModes:['AGE_9_12','AGE_13_17','ADULT'],outdoor:true,familyEligible:true},
{id:'move_outdoor_15',title:'OUTDOOR PORTAL',description:'15 minut ruchu na świeżym powietrzu: spacer, zabawa albo lekki trening.',kind:'OUTDOOR',minutes:15,skills:['ENDURANCE'],verification:'MIXED',difficulty:'EASY',ageModes:[...ALL],outdoor:true,familyEligible:true},
{id:'move_family_30',title:'FAMILY EXPEDITION',description:'30 minut wspólnej aktywności: spacer, rower, park lub basen.',kind:'FAMILY',minutes:30,skills:['ENDURANCE','COORDINATION'],verification:'PARENT_APPROVAL',difficulty:'EASY',ageModes:['AGE_6_8','AGE_9_12','AGE_13_17'],outdoor:true,familyEligible:true},
{id:'family_walk_45',title:'FAMILY EXPEDITION // WALK',description:'45 minut wspólnego spaceru w bezpiecznej przestrzeni.',kind:'FAMILY',minutes:45,skills:['ENDURANCE','COORDINATION'],verification:'PARENT_APPROVAL',difficulty:'EASY',ageModes:['AGE_6_8','AGE_9_12','AGE_13_17','ADULT'],outdoor:true,familyEligible:true},
{id:'family_bike_60',title:'FAMILY EXPEDITION // BIKE',description:'60 minut wspólnej jazdy rowerem na bezpiecznej trasie.',kind:'FAMILY',minutes:60,skills:['ENDURANCE','COORDINATION'],verification:'PARENT_APPROVAL',difficulty:'NORMAL',ageModes:['AGE_9_12','AGE_13_17','ADULT'],outdoor:true,familyEligible:true},
{id:'family_outdoor_45',title:'FAMILY EXPEDITION // OUTDOOR',description:'45 minut wspólnego ruchu na świeżym powietrzu.',kind:'FAMILY',minutes:45,skills:['ENDURANCE','BALANCE'],verification:'PARENT_APPROVAL',difficulty:'EASY',ageModes:['AGE_6_8','AGE_9_12','AGE_13_17','ADULT'],outdoor:true,familyEligible:true},
{id:'move_coord_10',title:'COORDINATION GRID',description:'10 minut prostych zmian kierunku, kroków i reakcji ruchowej.',kind:'OUTDOOR',minutes:10,skills:['COORDINATION','BALANCE'],verification:'TIMER',difficulty:'NORMAL',ageModes:['AGE_6_8','AGE_9_12','AGE_13_17'],outdoor:false,familyEligible:false},
{id:'move_endurance_20',title:'ENDURANCE PATH',description:'20 minut ciągłego ruchu w tempie dopasowanym do siebie.',kind:'WALK',minutes:20,skills:['ENDURANCE'],verification:'MIXED',difficulty:'NORMAL',ageModes:['AGE_9_12','AGE_13_17','ADULT'],outdoor:true,familyEligible:true},
];
