// SYSTEM 2.0 - Achievement Catalog
// Initial achievement definitions

import type { AchievementDefinition, TitleDefinition } from './types';

export const ACHIEVEMENT_CATEGORIES: Record<string, { name: string; order: number; icon: string }> = {
  QUESTS: { name: 'QUESTS', order: 1, icon: '▣' },
  EXPLORATION: { name: 'EXPLORATION', order: 2, icon: '◈' },
  CONSISTENCY: { name: 'CONSISTENCY', order: 3, icon: '▬' },
  PROGRESSION: { name: 'PROGRESSION', order: 4, icon: '▲' },
  BOSSES: { name: 'BOSSES', order: 5, icon: '▼' },
  FIELD_ACTIVITY: { name: 'FIELD ACTIVITY', order: 6, icon: '▣' },
  SPECIAL: { name: 'SPECIAL', order: 7, icon: '◆' },
};

// ============================================================
// ACHIEVEMENT DEFINITIONS
// ============================================================

export const ACHIEVEMENTS: readonly AchievementDefinition[] = [
  // ============ QUESTS ============
  {
    id: 'first_quest',
    name: 'FIRST STEPS',
    description: 'Complete your first quest',
    category: 'QUESTS',
    hidden: false,
    target: 1,
    progressKey: 'questsCompleted',
    requiredQuests: [],
    reward: { realXp: 50 },
    tier: 'COMMON',
    order: 1,
  },
  {
    id: 'quest_5',
    name: 'GETTING STARTED',
    description: 'Complete 5 quests',
    category: 'QUESTS',
    hidden: false,
    target: 5,
    progressKey: 'questsCompleted',
    requiredQuests: [],
    reward: { realXp: 100, skillXp: { WIL: 20 } },
    tier: 'COMMON',
    order: 2,
  },
  {
    id: 'quest_10',
    name: 'QUEST MASTER',
    description: 'Complete 10 quests',
    category: 'QUESTS',
    hidden: false,
    target: 10,
    progressKey: 'questsCompleted',
    requiredQuests: [],
    reward: { realXp: 250, skillXp: { WIL: 40, INT: 20 } },
    tier: 'UNCOMMON',
    order: 3,
  },
  {
    id: 'quest_25',
    name: 'QUEST VETERAN',
    description: 'Complete 25 quests',
    category: 'QUESTS',
    hidden: false,
    target: 25,
    progressKey: 'questsCompleted',
    requiredQuests: [],
    reward: { realXp: 500, skillXp: { WIL: 60, INT: 40 } },
    tier: 'RARE',
    order: 4,
  },
  {
    id: 'quest_50',
    name: 'QUEST LEGEND',
    description: 'Complete 50 quests',
    category: 'QUESTS',
    hidden: false,
    target: 50,
    progressKey: 'questsCompleted',
    requiredQuests: [],
    reward: { realXp: 1000, skillXp: { WIL: 100, INT: 60, STR: 40 } },
    tier: 'EPIC',
    order: 5,
  },
  {
    id: 'quest_100',
    name: 'CENTURION',
    description: 'Complete 100 quests',
    category: 'QUESTS',
    hidden: false,
    target: 100,
    progressKey: 'questsCompleted',
    requiredQuests: [],
    reward: { realXp: 2500, skillXp: { WIL: 150, INT: 100, STR: 80, VIT: 50 } },
    tier: 'LEGENDARY',
    order: 6,
  },

  // ============ EXPLORATION ============
  {
    id: 'first_sector',
    name: 'FIRST FOOTPRINT',
    description: 'Discover your first sector in SYSTEM WORLD',
    category: 'EXPLORATION',
    hidden: false,
    target: 1,
    progressKey: 'sectorsDiscovered',
    reward: { realXp: 50, skillXp: { VIT: 10 } },
    tier: 'COMMON',
    order: 1,
  },
  {
    id: 'explorer_5',
    name: 'PATHFINDER',
    description: 'Discover 5 sectors',
    category: 'EXPLORATION',
    hidden: false,
    target: 5,
    progressKey: 'sectorsDiscovered',
    reward: { realXp: 100, skillXp: { VIT: 20, RES: 10 } },
    tier: 'COMMON',
    order: 2,
  },
  {
    id: 'explorer_10',
    name: 'CARTOGRAPHER',
    description: 'Discover 10 sectors',
    category: 'EXPLORATION',
    hidden: false,
    target: 10,
    progressKey: 'sectorsDiscovered',
    reward: { realXp: 200, skillXp: { VIT: 40, RES: 20 } },
    tier: 'UNCOMMON',
    order: 3,
  },
  {
    id: 'explorer_25',
    name: 'FRONTIER WALKER',
    description: 'Discover 25 sectors',
    category: 'EXPLORATION',
    hidden: false,
    target: 25,
    progressKey: 'sectorsDiscovered',
    reward: { realXp: 500, skillXp: { VIT: 60, RES: 40, INT: 20 } },
    tier: 'RARE',
    order: 4,
  },
  {
    id: 'first_signal',
    name: 'SIGNAL HUNTER',
    description: 'Locate your first signal in SYSTEM WORLD',
    category: 'EXPLORATION',
    hidden: false,
    target: 1,
    progressKey: 'signalsLocated',
    requiredAchievements: ['first_sector'],
    reward: { realXp: 200, skillXp: { INT: 30, RES: 20 } },
    tier: 'UNCOMMON',
    order: 5,
  },
  {
    id: 'signal_master',
    name: 'SIGNAL MASTER',
    description: 'Locate 10 signals',
    category: 'EXPLORATION',
    hidden: false,
    target: 10,
    progressKey: 'signalsLocated',
    requiredAchievements: ['first_signal'],
    reward: { realXp: 500, skillXp: { INT: 60, RES: 40 } },
    tier: 'RARE',
    order: 6,
  },

  // ============ CONSISTENCY ============
  {
    id: 'first_streak',
    name: 'FIRST SPARK',
    description: 'Achieve a 1-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 1,
    progressKey: 'currentStreak',
    reward: { realXp: 25 },
    tier: 'COMMON',
    order: 1,
  },
  {
    id: 'streak_3',
    name: 'THREE PEAT',
    description: 'Achieve a 3-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 3,
    progressKey: 'currentStreak',
    reward: { realXp: 50, skillXp: { WIL: 15 } },
    tier: 'COMMON',
    order: 2,
  },
  {
    id: 'streak_7',
    name: 'WEEKLY WARRIOR',
    description: 'Achieve a 7-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 7,
    progressKey: 'currentStreak',
    reward: { realXp: 100, skillXp: { WIL: 30 } },
    tier: 'UNCOMMON',
    order: 3,
  },
  {
    id: 'streak_14',
    name: 'FORTNIGHT',
    description: 'Achieve a 14-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 14,
    progressKey: 'currentStreak',
    reward: { realXp: 250, skillXp: { WIL: 50, VIT: 30 } },
    tier: 'RARE',
    order: 4,
  },
  {
    id: 'streak_30',
    name: 'UNBROKEN',
    description: 'Achieve a 30-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 30,
    progressKey: 'currentStreak',
    reward: { realXp: 500, skillXp: { WIL: 100, VIT: 50 } },
    tier: 'EPIC',
    order: 5,
  },
  {
    id: 'streak_60',
    name: 'IRON WILL',
    description: 'Achieve a 60-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 60,
    progressKey: 'currentStreak',
    reward: { realXp: 1000, skillXp: { WIL: 150, VIT: 100, STR: 100 } },
    tier: 'EPIC',
    order: 6,
  },
  {
    id: 'streak_100',
    name: 'CENTURION',
    description: 'Achieve a 100-day streak',
    category: 'CONSISTENCY',
    hidden: false,
    target: 100,
    progressKey: 'currentStreak',
    reward: { realXp: 2500, skillXp: { WIL: 250, VIT: 200, STR: 150 } },
    tier: 'LEGENDARY',
    order: 7,
  },

  // ============ PROGRESSION ============
  {
    id: 'level_5',
    name: 'RISING STAR',
    description: 'Reach level 5',
    category: 'PROGRESSION',
    hidden: false,
    target: 5,
    progressKey: 'realLevel',
    reward: { realXp: 100, skillXp: { INT: 20 } },
    tier: 'COMMON',
    order: 1,
  },
  {
    id: 'level_10',
    name: 'ASCENDANT',
    description: 'Reach level 10',
    category: 'PROGRESSION',
    hidden: false,
    target: 10,
    progressKey: 'realLevel',
    reward: { realXp: 200, skillXp: { INT: 40, WIL: 20 } },
    tier: 'UNCOMMON',
    order: 2,
  },
  {
    id: 'level_25',
    name: 'VETERAN',
    description: 'Reach level 25',
    category: 'PROGRESSION',
    hidden: false,
    target: 25,
    progressKey: 'realLevel',
    reward: { realXp: 500, skillXp: { INT: 80, WIL: 40, CHA: 40 } },
    tier: 'RARE',
    order: 3,
  },
  {
    id: 'level_50',
    name: 'MASTER',
    description: 'Reach level 50',
    category: 'PROGRESSION',
    hidden: false,
    target: 50,
    progressKey: 'realLevel',
    reward: { realXp: 1000, skillXp: { INT: 150, WIL: 100, CHA: 80 } },
    tier: 'EPIC',
    order: 4,
  },
  {
    id: 'level_100',
    name: 'GRANDMASTER',
    description: 'Reach level 100',
    category: 'PROGRESSION',
    hidden: false,
    target: 100,
    progressKey: 'realLevel',
    reward: { realXp: 5000, skillXp: { INT: 300, WIL: 200, CHA: 150, STR: 150 } },
    tier: 'LEGENDARY',
    order: 5,
  },
  {
    id: 'xp_1000',
    name: 'THOUSAND STEPS',
    description: 'Earn 1,000 total REAL XP',
    category: 'PROGRESSION',
    hidden: false,
    target: 1000,
    progressKey: 'totalRealXp',
    reward: { realXp: 100, skillXp: { INT: 30 } },
    tier: 'COMMON',
    order: 6,
  },
  {
    id: 'xp_10000',
    name: 'TEN THOUSAND',
    description: 'Earn 10,000 total REAL XP',
    category: 'PROGRESSION',
    hidden: false,
    target: 10000,
    progressKey: 'totalRealXp',
    reward: { realXp: 1000, skillXp: { INT: 200, WIL: 100 } },
    tier: 'EPIC',
    order: 7,
  },
  {
    id: 'verified_10',
    name: 'VERIFIED',
    description: 'Complete 10 verified quests',
    category: 'PROGRESSION',
    hidden: false,
    target: 10,
    progressKey: 'verifiedQuestCount',
    reward: { realXp: 200, skillXp: { WIL: 40, RES: 30 } },
    tier: 'UNCOMMON',
    order: 8,
  },
  {
    id: 'verified_50',
    name: 'VERIFICATION MASTER',
    description: 'Complete 50 verified quests',
    category: 'PROGRESSION',
    hidden: false,
    target: 50,
    progressKey: 'verifiedQuestCount',
    reward: { realXp: 1000, skillXp: { WIL: 100, RES: 80, INT: 50 } },
    tier: 'EPIC',
    order: 9,
  },

  // ============ BOSSES ============
  {
    id: 'first_boss',
    name: 'BOSS HUNTER',
    description: 'Defeat your first boss',
    category: 'BOSSES',
    hidden: false,
    target: 1,
    progressKey: 'bossesDefeated',
    requiredAchievements: ['first_boss_encounter'],
    reward: { realXp: 500, skillXp: { STR: 50, VIT: 40, WIL: 40 } },
    tier: 'RARE',
    order: 1,
  },
  {
    id: 'boss_3',
    name: 'BOSS SLAYER',
    description: 'Defeat 3 bosses',
    category: 'BOSSES',
    hidden: false,
    target: 3,
    progressKey: 'bossesDefeated',
    requiredAchievements: ['first_boss'],
    reward: { realXp: 1000, skillXp: { STR: 80, VIT: 60, WIL: 60 } },
    tier: 'EPIC',
    order: 2,
  },
  {
    id: 'boss_5',
    name: 'BOSS DESTROYER',
    description: 'Defeat 5 bosses',
    category: 'BOSSES',
    hidden: false,
    target: 5,
    progressKey: 'bossesDefeated',
    requiredAchievements: ['boss_3'],
    reward: { realXp: 2500, skillXp: { STR: 150, VIT: 120, WIL: 100, CHA: 100 } },
    tier: 'LEGENDARY',
    order: 3,
  },
  {
    id: 'first_boss_encounter',
    name: 'FIRST ENCOUNTER',
    description: 'Start your first boss battle',
    category: 'BOSSES',
    hidden: false,
    target: 1,
    progressKey: 'bossEncounters',
    reward: { realXp: 0 },
    tier: 'COMMON',
    order: 0,
  },

  // ============ FIELD ACTIVITY ============
  {
    id: 'walk_1km',
    name: 'FIRST KILOMETER',
    description: 'Walk 1 kilometer in a single field quest',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 1,
    progressKey: 'longestWalkQuestKm',
    requiredAchievements: [],
    reward: { realXp: 50, skillXp: { VIT: 20 } },
    tier: 'COMMON',
    order: 1,
  },
  {
    id: 'walk_10km',
    name: 'MARATHON WALKER',
    description: 'Walk 10 kilometers total in field quests',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 10,
    progressKey: 'fieldQuestsDistance',
    reward: { realXp: 200, skillXp: { VIT: 40, STR: 30 } },
    tier: 'UNCOMMON',
    order: 2,
  },
  {
    id: 'walk_50km',
    name: 'ULTRA WALKER',
    description: 'Walk 50 kilometers total in field quests',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 50,
    progressKey: 'fieldQuestsDistance',
    reward: { realXp: 500, skillXp: { VIT: 100, STR: 80 } },
    tier: 'RARE',
    order: 3,
  },
  {
    id: 'run_5km',
    name: 'SPRINTER',
    description: 'Run 5 kilometers in a single field quest',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 5,
    progressKey: 'longestRunQuestKm',
    requiredAchievements: ['walk_1km'],
    reward: { realXp: 200, skillXp: { VIT: 40, STR: 30 } },
    tier: 'UNCOMMON',
    order: 4,
  },
  {
    id: 'run_20km',
    name: 'ENDURANCE RUNNER',
    description: 'Run 20 kilometers total in field quests',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 20,
    progressKey: 'runQuestsDistance',
    requiredAchievements: ['run_5km'],
    reward: { realXp: 500, skillXp: { VIT: 80, STR: 60 } },
    tier: 'RARE',
    order: 5,
  },
  {
    id: 'field_quest_10',
    name: 'FIELD VETERAN',
    description: 'Complete 10 field quests',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 10,
    progressKey: 'fieldQuestsCompleted',
    reward: { realXp: 200, skillXp: { VIT: 40, RES: 30 } },
    tier: 'UNCOMMON',
    order: 5,
  },
  {
    id: 'field_quest_50',
    name: 'FIELD MASTER',
    description: 'Complete 50 field quests',
    category: 'FIELD_ACTIVITY',
    hidden: false,
    target: 50,
    progressKey: 'fieldQuestsCompleted',
    reward: { realXp: 1000, skillXp: { VIT: 100, RES: 80, STR: 60 } },
    tier: 'EPIC',
    order: 6,
  },

  // ============ SPECIAL / HIDDEN ============
  {
    id: 'extra_mile',
    name: 'EXTRA MILE',
    description: 'Complete a movement daily quest with 125% of target distance',
    category: 'SPECIAL',
    hidden: false,
    target: 1,
    progressKey: 'extraMileCompleted',
    requiredAchievements: ['walk_1km'],
    reward: { realXp: 50, skillXp: { WIL: 40 } },
    tier: 'UNCOMMON',
    order: 1,
  },
  {
    id: 'no_turning_back',
    name: 'NO TURNING BACK',
    description: 'Complete a field quest after previously failing one',
    category: 'SPECIAL',
    hidden: true,
    target: 1,
    progressKey: 'comebackCompleted',
    requiredAchievements: [],
    reward: { realXp: 60, skillXp: { WIL: 50 } },
    tier: 'RARE',
    order: 2,
  },
  {
    id: 'perfect_week',
    name: 'PERFECT WEEK',
    description: 'Complete all daily quests for 7 consecutive days',
    category: 'SPECIAL',
    hidden: false,
    target: 1,
    progressKey: 'perfectWeeks',
    requiredAchievements: ['streak_7'],
    reward: { realXp: 500, skillXp: { WIL: 100, INT: 50 } },
    tier: 'EPIC',
    order: 3,
  },
  {
    id: 'early_bird',
    name: 'EARLY BIRD',
    description: 'Complete a daily quest before 8 AM',
    category: 'SPECIAL',
    hidden: false,
    target: 5,
    progressKey: 'earlyBirdCount',
    reward: { realXp: 100, skillXp: { WIL: 30 } },
    tier: 'UNCOMMON',
    order: 4,
  },
  {
    id: 'night_owl',
    name: 'NIGHT OWL',
    description: 'Complete a daily quest after 10 PM',
    category: 'SPECIAL',
    hidden: false,
    target: 5,
    progressKey: 'nightOwlCount',
    reward: { realXp: 100, skillXp: { INT: 30 } },
    tier: 'UNCOMMON',
    order: 5,
  },
  {
    id: 'completionist',
    name: 'COMPLETIONIST',
    description: 'Unlock all non-hidden achievements',
    category: 'SPECIAL',
    hidden: true,
    target: 1,
    progressKey: 'allAchievementsUnlocked',
    requiredAchievements: [],
    reward: { realXp: 5000, skillXp: { STR: 200, VIT: 200, INT: 200, WIL: 200, CHA: 200, CRE: 200, RES: 200 } },
    tier: 'LEGENDARY',
    order: 6,
  },
];

// ============================================================
// TITLE DEFINITIONS
// ============================================================

export const TITLES: readonly TitleDefinition[] = [
  {
    id: 'unawakened',
    name: 'UNAWAKENED',
    description: 'The starting state for all players',
    isDefault: true,
    order: 0,
  },
  {
    id: 'awakened',
    name: 'AWAKENED',
    description: 'Completed the First Awakening',
    unlockedByAchievement: 'first_quest',
    order: 1,
  },
  {
    id: 'quest_hunter',
    name: 'QUEST HUNTER',
    description: 'Completed 10 quests',
    unlockedByAchievement: 'quest_10',
    order: 2,
  },
  {
    id: 'pathfinder',
    name: 'PATHFINDER',
    description: 'Discovered 10 sectors',
    unlockedByAchievement: 'explorer_10',
    order: 3,
  },
  {
    id: 'signal_hunter',
    name: 'SIGNAL HUNTER',
    description: 'Located first signal',
    unlockedByAchievement: 'first_signal',
    order: 4,
  },
  {
    id: 'unbroken',
    name: 'UNBROKEN',
    description: 'Achieved a 30-day streak',
    unlockedByAchievement: 'streak_30',
    order: 5,
  },
  {
    id: 'centurion',
    name: 'CENTURION',
    description: 'Achieved a 100-day streak',
    unlockedByAchievement: 'streak_100',
    order: 6,
  },
  {
    id: 'boss_slayer',
    name: 'BOSS SLAYER',
    description: 'Defeated 3 bosses',
    unlockedByAchievement: 'boss_3',
    order: 7,
  },
  {
    id: 'boss_destroyer',
    name: 'BOSS DESTROYER',
    description: 'Defeated 5 bosses',
    unlockedByAchievement: 'boss_5',
    order: 8,
  },
  {
    id: 'quest_legend',
    name: 'QUEST LEGEND',
    description: 'Completed 100 quests',
    unlockedByAchievement: 'quest_100',
    order: 9,
  },
  {
    id: 'grandmaster',
    name: 'GRANDMASTER',
    description: 'Reached level 100',
    unlockedByAchievement: 'level_100',
    order: 10,
  },
  {
    id: 'signal_master',
    name: 'SIGNAL MASTER',
    description: 'Located 10 signals',
    unlockedByAchievement: 'signal_master',
    order: 12,
  },
  {
    id: 'wallbreaker',
    name: 'WALLBREAKER',
    description: 'Defeated THE FIRST WALL boss',
    unlockedByAchievement: 'boss_5',
    order: 13,
  },
  {
    id: 'completionist',
    name: 'COMPLETIONIST',
    description: 'Unlocked all non-hidden achievements',
    unlockedByAchievement: 'completionist',
    order: 14,
  },
];
